#!/usr/bin/python3

# Reverse a String
# Write a Python program to reverse a string.
input="Hello World"
print(input[::-1])

# ========================================================
# 2. Check if a String is a Palindrome
# Write a Python program to check if a string is a palindrome (reads the same backward as forward).

input="test"
print(input==input[::-1])


# ========================================================
# 3.Remove Duplicates from a String
# Write a Python program to remove duplicate characters from a string.

input="HelloFromTest Test"
print(set(input))

# =========================================================
# 4.Find the Longest Word in a String
# Write a Python program to find the longest word in a given string.
# text = "Python is a great programming language"
# #Output=programming

input="Python is a great programming language"
text = sorted(input.split(" "), reverse=True, key=len)[0]

# =========================================================== 
# 5.Find Common Elements Between Two Tuples
# Write a Python program to find common elements between two tuples.
# ``` python
tuple1 = (1, 2, 3)
tuple2 = (2, 3, 4)
tuple3 = set(tuple1) & set(tuple2)



# =========================================================== 
# 6.Find the Maximum and Minimum Value in a Dictionary 
# Write a Python program to find the maximum and minimum value in a dictionary. 
# my_dict = {"a": 10, "b": 20, "c": 5}  
# Min= 5  , max=20 

my_dict = {"a": 10, "b": 20, "c": 5}  
print("Min:", min(my_dict.values()), "Max:", max(my_dict.values()))





# 7- Merge Two Dictionaries 
# Write a Python program to merge two dictionaries. 
# dict1 = {"a": 1, "b": 2} 
# dict2 = {"c": 3, "d": 4} 
# # Output: {'a': 1, 'b': 2, 'c': 3, 'd': 4} 
dict1 = {"a": 1, "b": 2} 
dict2 = {"c": 3, "d": 4} 
print(dict(list(dict1.items()) + list(dict2.items())) )
 

# 8- Find Common Keys in Two Dictionaries 
# Write a Python program to find common keys in two dictionaries. 
# dict1 = {"a": 1, "b": 2, "c": 3} 
# dict2 = {"b": 2, "c": 4, "d": 5} 
# #Output: {'b', 'c'} 
dict1 = {"a": 1, "b": 2, "c": 3} 
dict2 = {"b": 2, "c": 4, "d": 5} 

tuple2 = set(dict1.keys()) & set(dict2.keys())

print(tuple2)
 

# 9- takes a string and prints the longest 
# alphabetical ordered substring occured. 
# For example, if the string is 'abdulrahman' then the output is: 
# Longest substring in alphabetical order is: abdu 
text = list("kmlmaskldmlkasabcdeabcdefghijklmnopqrfghkasdaasdlkamsdkasmkdabcdefghijksdabcdefghijklmnopqrstuv")

start = 0
length = 0
current_length = 1
prev_char = " "

for index, char in enumerate(text):
    if ord(char) == ord(prev_char) + 1:
        current_length += 1
    else:
        if current_length > length:
            length = current_length
            start = index - length
        current_length = 1
    
    prev_char = char

if current_length > length:
    length = current_length
    start = len(text) - length

end = start + length
print("Longest substring is:", "".join(text[start:end]))
